project_id = "rltkxwswlvuzwmmbqwkr"

[functions.evolution-api]
verify_jwt = false

[functions.openai-chat]
verify_jwt = true

[functions.test-evolution]
verify_jwt = false

[functions.force-maturation]
verify_jwt = false

[functions.process-broadcast-campaign]
verify_jwt = true

[functions.send-broadcast-messages]
verify_jwt = true