project_id = "rltkxwswlvuzwmmbqwkr"

[functions.evolution-api]
verify_jwt = false

[functions.openai-chat]
verify_jwt = true

[functions.test-openai]
verify_jwt = false

[functions.test-evolution]
verify_jwt = false

[functions.force-maturation]
verify_jwt = false